INFO:root:{'object': 'page', 'entry': [{'changes': [{'value': {'sender_id': 707499519337800, 'parent_id': '707499519337800_1077558675665214', 'post_id': '707499519337800_1077558675665214', 'verb': 'remove', 'created_time': 1473126570, 'item': 'like'}, 'field': 'feed'}], 'id': '707499519337800', 'time': 1473126570}]}
INFO:root:None
INFO:root:{'object': 'page', 'entry': [{'id': '707499519337800', 'changes': [{'field': 'feed', 'value': {'sender_id': 707499519337800, 'created_time': 1473129433, 'post_id': '707499519337800_1077558675665214', 'sender_name': 'GrumpyTravels', 'verb': 'add', 'parent_id': '707499519337800_1077558675665214', 'item': 'like'}}], 'time': 1473129433}]}
INFO:root:{'object': 'page', 'entry': [{'changes': [{'field': 'feed', 'value': {'parent_id': '707499519337800_1077558675665214', 'item': 'like', 'verb': 'remove', 'sender_id': 707499519337800, 'created_time': 1473130509, 'post_id': '707499519337800_1077558675665214'}}], 'time': 1473130509, 'id': '707499519337800'}]}
ERROR:app:Exception on /webhooks [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 25, in webhooks_receive
    DB.save_webhooks_update(json)
  File "./DB.py", line 17, in save_webhooks_update
    items
NameError: name 'items' is not defined
INFO:root:{'object': 'page', 'entry': [{'changes': [{'field': 'feed', 'value': {'parent_id': '707499519337800_1077558675665214', 'item': 'like', 'verb': 'remove', 'sender_id': 707499519337800, 'created_time': 1473130509, 'post_id': '707499519337800_1077558675665214'}}], 'time': 1473130509, 'id': '707499519337800'}]}
ERROR:app:Exception on /webhooks [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 25, in webhooks_receive
    DB.save_webhooks_update(json)
  File "./DB.py", line 17, in save_webhooks_update
    items
NameError: name 'items' is not defined
INFO:root:{'entry': [{'time': 1473130563, 'changes': [{'value': {'item': 'like', 'created_time': 1473130563, 'verb': 'add', 'post_id': '707499519337800_1077558675665214', 'parent_id': '707499519337800_1077558675665214', 'sender_name': 'GrumpyTravels', 'sender_id': 707499519337800}, 'field': 'feed'}], 'id': '707499519337800'}], 'object': 'page'}
ERROR:app:Exception on /webhooks [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 25, in webhooks_receive
    DB.save_webhooks_update(json)
  File "./DB.py", line 26, in save_webhooks_update
    insert_webhooks_update(cursor, target_id, topic, time, field, value)
  File "./DB.py", line 45, in insert_webhooks_update
    cursor.execute(query, target_id, topic, field, value is not None, value)
TypeError: execute() takes from 2 to 4 positional arguments but 7 were given
INFO:root:{'entry': [{'time': 1473130563, 'changes': [{'value': {'item': 'like', 'created_time': 1473130563, 'verb': 'add', 'post_id': '707499519337800_1077558675665214', 'parent_id': '707499519337800_1077558675665214', 'sender_name': 'GrumpyTravels', 'sender_id': 707499519337800}, 'field': 'feed'}], 'id': '707499519337800'}], 'object': 'page'}
ERROR:app:Exception on /webhooks [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 25, in webhooks_receive
    DB.save_webhooks_update(json)
  File "./DB.py", line 26, in save_webhooks_update
    insert_webhooks_update(cursor, target_id, topic, time, field, value)
  File "./DB.py", line 45, in insert_webhooks_update
    cursor.execute(query, target_id, topic, field, value is not None, value)
TypeError: execute() takes from 2 to 4 positional arguments but 7 were given
